name: Setup R
description: Common steps for installing R and project dependencies
runs:
  using: "composite"
  steps:
    - name: Install system packages for R
      shell: bash
      run: sudo apt-get install --yes --quiet libmagick++-dev libpoppler-cpp-dev
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'
    - name: Install R Dependencies
      uses: r-lib/actions/setup-renv@v2
      with:
        working-directory: website/skirolly/
